  const rating_committee_meetings = [
    {
      id: "e4f6cec0-ac80-48ec-b056-ce4d5e922a12",
      progress: "Ongoing",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 1,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
    {
      id: 2,
      progress: "Completed",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 2,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
    {
      id: 3,
      progress: "Scheduled",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 3,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
    {
      id: 4,
      progress: "Ongoing",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 4,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
    {
      id: 5,
      progress: "Ongoing",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 5,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
    {
      id: 6,
      progress: "Ongoing",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 6,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
    {
      id: 7,
      progress: "Ongoing",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 7,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
    {
      id: 8,
      progress: "Completed",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 8,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
    {
      id: 9,
      progress: "Ongoing",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 9,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
    {
      id: 10,
      progress: "Scheduled",
      dateTime: "29/12/22  15:00",
      committeeType: "Internal",
      category: "A1 Committee",
      numberOfCases: 10,
      action: [
        {
          id: "e4f6cec0-a180-48ec-b056-ce4d5e922a12",
          title: "Committee Member",
          route: "/dashboard/rating-committee/meetings/committee-member",
        },
        {
          id: "e4f6cec0-a280-48ec-b056-ce4d5e922a12", title: "View Agenda", route: "/dashboard/rating-committee/meetings/view-agenda" },
        {
          id: "e4f6cec0-a380-48ec-b056-ce4d5e922a12", title: "Voting", route: "/dashboard/rating-committee/committee-voting" },
        {
          id: "e4f6cec0-a480-48ec-b056-ce4d5e922a12", title: "Register", route: "/dashboard/rating-committee/rating-register" },
        {
          id: "e4f6cec0-a580-48ec-b056-ce4d5e922a12", title: "Minutes", route: "/dashboard/rating-committee/committee-minutes" },
      ]
    },
  ];

  const committee_agenda =  [
    {
      id: 1,
      nameOfCompany: "Ultra Tech",
      mandateID: "2020-2021/1/1003",
      category: "NCD Ban / Bank Facility",
      subCategory: "Fund Based",
      instrumentFacility: "NCD Ban / Bank Facility",
      size: "100.0/200.00",
      agendaType: "Initial",
      ratingRecommendation: "BBB",
      outlook: "Stable",
      ratingRecommendation2: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "-",
    },
    {
      id: 2,
      nameOfCompany: "Kilburn Engineeering Ltd.",
      mandateID: "2020-2021/1/1003",
      category: "NCD Ban / Bank Facility",
      subCategory: "Fund Based",
      instrumentFacility: "NCD Ban / Bank Facility",
      size: "100.0/200.00",
      agendaType: "Initial",
      ratingRecommendation: "BBB",
      outlook: "Stable",
      ratingRecommendation2: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "-",
    },
    {
      id: 3,
      nameOfCompany: "P & R Infraproject P Ltd",
      mandateID: "2020-2021/1/1003",
      category: "NCD Ban / Bank Facility",
      subCategory: "Fund Based",
      instrumentFacility: "NCD Ban / Bank Facility",
      size: "100.0/200.00",
      agendaType: "Initial",
      ratingRecommendation: "BBB",
      outlook: "Stable",
      ratingRecommendation2: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "-",
    },
    {
      id: 4,
      nameOfCompany: "Shivam Iron & Steel Company limited",
      mandateID: "2020-2021/1/1003",
      category: "NCD Ban / Bank Facility",
      subCategory: "Fund Based",
      instrumentFacility: "NCD Ban / Bank Facility",
      size: "100.0/200.00",
      agendaType: "Initial",
      ratingRecommendation: "BBB",
      outlook: "Stable",
      ratingRecommendation2: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "-",
    },
    {
      id: 5,
      nameOfCompany: "Finkurve Fin. Services Ltd.",
      mandateID: "2020-2021/1/1003",
      category: "NCD Ban / Bank Facility",
      subCategory: "Fund Based",
      instrumentFacility: "NCD Ban / Bank Facility",
      size: "100.0/200.00",
      agendaType: "Initial",
      ratingRecommendation: "BBB",
      outlook: "Stable",
      ratingRecommendation2: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "-",
    }]

    const rating_verification =  [
      {
        id: 1,
        nameOfCompany: "Ultra Tech",
        mandateId: "2020-2021/1/1003",
        from: "Rupesh",
        pendingDays: 0,
        agenda: "New",
        stage: "GH to verify rating",
        remarks: "--",
        ratingNote: true,
        annual: true,
        mom: "Verify Minutes",
        rl: true,
        pr: false,
        rr: false,
      },
      {
        id: 2,
        nameOfCompany: "Kilburn Engineering Ltd.",
        mandateId: "2020-2021/1/1003",
        from: "Rupesh",
        pendingDays: 0,
        agenda: "New",
        stage: "GH to verify rating",
        remarks: "--",
        ratingNote: true,
        annual: true,
        mom: "Verify Minutes",
        rl: true,
        pr: true,
        rr: false,
      },
      {
        id: 3,
        nameOfCompany: "P & R Infraproject P Ltd.",
        mandateId: "2020-2021/1/1003",
        from: "Rupesh",
        pendingDays: 0,
        agenda: "New",
        stage: "GH to verify rating",
        remarks: "--",
        ratingNote: true,
        annual: true,
        mom: "Verify Minutes",
        rl: true,
        pr: true,
        rr: false,
      },
      {
        id: 4,
        nameOfCompany: "Devaraja Group",
        mandateId: "2020-2021/1/1003",
        from: "Rupesh",
        pendingDays: 0,
        agenda: "New",
        stage: "GH to verify rating",
        remarks: "--",
        ratingNote: true,
        annual: true,
        mom: "Verify Minutes",
        rl: true,
        pr: false,
        rr: true,
      },
    ];

    const committee_voting = [
      {
        id: 1,
        nameOfCompany: "Ultra Tech",
        mandateId: "2020-2021/1/1003",
        instrumentType: "One",
        groupHead: "Uttkarsh",
        ratingTeamRecommendation: "BB+",
        ratingTeamNonCooperation: "--",
        rcMembersRating: "Rating A",
        rcMembersOutput: "Stable",
        remarks: "",
        dissent: "",
        corfStandaloneCategory: "--",
        corfFinalCategory: "--",
      },
      {
        id: 2,
        nameOfCompany: "Kilburn Engineeering Ltd.",
        mandateId: "2020-2021/1/1003",
        instrumentType: "One",
        groupHead: "Uttkarsh",
        ratingTeamRecommendation: "BB+",
        ratingTeamNonCooperation: "--",
        rcMembersRating: "Rating A",
        rcMembersOutput: "Stable",
        remarks: "",
        dissent: "",
        corfStandaloneCategory: "--",
        corfFinalCategory: "--",
      },
      {
        id: 3,
        nameOfCompany: "P & R Infraproject P Ltd",
        mandateId: "2020-2021/1/1003",
        instrumentType: "One",
        groupHead: "Uttkarsh",
        ratingTeamRecommendation: "BB+",
        ratingTeamNonCooperation: "--",
        rcMembersRating: "Rating A",
        rcMembersOutput: "Stable",
        remarks: "",
        dissent: "",
        corfStandaloneCategory: "--",
        corfFinalCategory: "--",
      },
      {
        id: 4,
        nameOfCompany: "Shivam Iron & Steel Company limited",
        mandateId: "2020-2021/1/1003",
        instrumentType: "One",
        groupHead: "Uttkarsh",
        ratingTeamRecommendation: "BB+",
        ratingTeamNonCooperation: "--",
        rcMembersRating: "Rating A",
        rcMembersOutput: "Stable",
        remarks: "",
        dissent: "",
        corfStandaloneCategory: "--",
        corfFinalCategory: "--",
      },
      {
        id: 5,
        nameOfCompany: "Finkurve Fin. Services Ltd.",
        mandateId: "2020-2021/1/1003",
        instrumentType: "One",
        groupHead: "Uttkarsh",
        ratingTeamRecommendation: "BB+",
        ratingTeamNonCooperation: "--",
        rcMembersRating: "Rating A",
        rcMembersOutput: "Stable",
        remarks: "",
        dissent: "",
        corfStandaloneCategory: "--",
        corfFinalCategory: "--",
      },
      {
        id: 6,
        nameOfCompany: "Silver Touch Technologies Ltd.",
        mandateId: "2020-2021/1/1003",
        instrumentType: "One",
        groupHead: "Uttkarsh",
        ratingTeamRecommendation: "BB+",
        ratingTeamNonCooperation: "--",
        rcMembersRating: "Rating A",
        rcMembersOutput: "Stable",
        remarks: "",
        dissent: "",
        corfStandaloneCategory: "--",
        corfFinalCategory: "--",
      },
    ];

  const committee_minutes = [
    {
      id: 5,
      company: "Ultra Tech",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }, 
    {
      id: 6,
      company: "Kilburn Engineeering Ltd.",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }, 
    {
      id: 6,
      company: "P & R Infraproject P Ltd",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }, 
    {
      id: 6,
      company: "Shivam Iron & Steel Company limited",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }, 
    {
      id: 6,
      company: "Finkurve Fin. Services Ltd.",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }, 
    {
      id: 6,
      company: "Silver Touch Technologies Ltd.",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }, 
    {
      id: 6,
      company: "Devaraja Group",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }, 
    {
      id: 6,
      company: "Sri Devaraja Agro Industrie",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }, 
    {
      id: 6,
      company: "Ultra Tech",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }, 
    {
      id: 6,
      company: "Ultra Tech",
      ratingDate: "08 Jan 2023",
      committeeType: "Internal",
      category: "A1",
      ratingAssigned: "BBB",
      instrumentFacility: "Term Loan",
      size: "100.0/200.00",
      agendaType: "Initial",
      outlook: "Stable",
      ratingRecommendation: "BBB",
      location: "Mumbai",
      modelRating: "BBB",
      outlook2: "Stable",
      modelRating2: "BBB",
      previousRating: "BBB",
      outlook3: "Stable",
      previousRating2: "BBB",
      meetingType: "Online",
      votingDone: "Yes",
    }
]

  module.exports = {
    rating_committee_meetings,
    committee_agenda,
    rating_verification,
    committee_voting,
    committee_minutes
  }